import type { Vocabulary, WordItem } from './types'

const srs = () => ({
  repetition: 0,
  interval: 1,
  easeFactor: 2.5,
  nextReview: 0,
})

type LearningEntry = readonly [
  id: string,
  sourceText: string,
  targetText: string,
]

const basicEntries = [
  ['kz_001', 'otbasy', 'семья'],
  ['kz_002', 'ata-ana', 'родители'],
  ['kz_003', 'ağa', 'старший брат'],
  ['kz_004', 'ini', 'младший брат'],
  ['kz_005', 'äke', 'отец'],
  ['kz_006', 'ana', 'мать'],
  ['kz_007', 'dos', 'друг'],
  ['kz_008', 'körshi', 'сосед'],
  ['kz_009', 'qala', 'город'],
  ['kz_010', 'auyl', 'село'],
  ['kz_011', 'köshe', 'улица'],
  ['kz_012', 'jol', 'дорога'],
  ['kz_013', 'üi', 'дом'],
  ['kz_014', 'bölme', 'комната'],
  ['kz_015', 'as üi', 'кухня'],
  ['kz_016', 'esik', 'дверь'],
  ['kz_017', 'terezе', 'окно'],
  ['kz_018', 'üstеl', 'стол'],
  ['kz_019', 'oryndyq', 'стул'],
  ['kz_020', 'tösek', 'кровать'],
  ['kz_021', 'mektep', 'школа'],
  ['kz_022', 'sabaq', 'урок'],
  ['kz_023', 'muğalim', 'учитель'],
  ['kz_024', 'oqushy', 'ученик'],
  ['kz_025', 'kitap', 'книга'],
  ['kz_026', 'däpter', 'тетрадь'],
  ['kz_027', 'qalam', 'ручка'],
  ['kz_028', 'sömke', 'сумка'],
  ['kz_029', 'jumys', 'работа'],
  ['kz_030', 'keñse', 'офис'],
  ['kz_031', 'düken', 'магазин'],
  ['kz_032', 'bazar', 'рынок'],
  ['kz_033', 'aqsha', 'деньги'],
  ['kz_034', 'bağa', 'цена'],
  ['kz_035', 'nan', 'хлеб'],
  ['kz_036', 'su', 'вода'],
  ['kz_037', 'shai', 'чай'],
  ['kz_038', 'süt', 'молоко'],
  ['kz_039', 'alma', 'яблоко'],
  ['kz_040', 'et', 'мясо'],
  ['kz_041', 'balyq', 'рыба'],
  ['kz_042', 'köje', 'суп'],
  ['kz_043', 'tuz', 'соль'],
  ['kz_044', 'tätti', 'сладкий'],
  ['kz_045', 'ülken', 'большой'],
  ['kz_046', 'kishkentai', 'маленький'],
  ['kz_047', 'jaña', 'новый'],
  ['kz_048', 'eski', 'старый'],
  ['kz_049', 'jaqsy', 'хороший'],
  ['kz_050', 'jaman', 'плохой'],
  ['kz_051', 'ystyq', 'горячий'],
  ['kz_052', 'suuyq', 'холодный'],
  ['kz_053', 'jyly', 'тёплый'],
  ['kz_054', 'tez', 'быстро'],
  ['kz_055', 'jai', 'медленно'],
  ['kz_056', 'bugin', 'сегодня'],
  ['kz_057', 'erteñ', 'завтра'],
  ['kz_058', 'keshe', 'вчера'],
  ['kz_059', 'tañ', 'утро'],
  ['kz_060', 'kesh', 'вечер'],
  ['kz_061', 'tün', 'ночь'],
  ['kz_062', 'uaqyt', 'время'],
  ['kz_063', 'sagat', 'час'],
  ['kz_064', 'aptа', 'неделя'],
  ['kz_065', 'ai', 'месяц'],
  ['kz_066', 'jyl', 'год'],
  ['kz_067', 'avtobus', 'автобус'],
  ['kz_068', 'kölik', 'машина'],
  ['kz_069', 'poiyz', 'поезд'],
  ['kz_070', 'äuejai', 'аэропорт'],
  ['kz_071', 'bilet', 'билет'],
  ['kz_072', 'däriger', 'врач'],
  ['kz_073', 'auruhana', 'больница'],
  ['kz_074', 'däri', 'лекарство'],
  ['kz_075', 'telefon', 'телефон'],
  ['kz_076', 'habar', 'сообщение'],
  ['kz_077', 'suraq', 'вопрос'],
  ['kz_078', 'jauap', 'ответ'],
  ['kz_079', 'til', 'язык'],
  ['kz_080', 'söz', 'слово'],
  ['kz_081', 'at', 'имя'],
  ['kz_082', 'el', 'страна'],
  ['kz_083', 'özen', 'река'],
  ['kz_084', 'tau', 'гора'],
  ['kz_085', 'orman', 'лес'],
  ['kz_086', 'saiasatbaq', 'парк'],
  ['kz_087', 'kün', 'солнце'],
  ['kz_088', 'jañbyr', 'дождь'],
  ['kz_089', 'qar', 'снег'],
  ['kz_090', 'jel', 'ветер'],
  ['kz_091', 'oqu', 'читать'],
  ['kz_092', 'jazu', 'писать'],
  ['kz_093', 'aitu', 'говорить'],
  ['kz_094', 'tyñdau', 'слушать'],
  ['kz_095', 'köru', 'видеть'],
  ['kz_096', 'baru', 'идти'],
  ['kz_097', 'kelu', 'приходить'],
  ['kz_098', 'satyp alu', 'покупать'],
  ['kz_099', 'izdeu', 'искать'],
  ['kz_100', 'tüsinu', 'понимать'],
] as const satisfies readonly LearningEntry[]

const verbEntries = [
  ['kz_verbs_001', 'oqu', 'читать'],
  ['kz_verbs_002', 'jazu', 'писать'],
  ['kz_verbs_003', 'aitu', 'говорить'],
  ['kz_verbs_004', 'tyñdau', 'слушать'],
  ['kz_verbs_005', 'köru', 'видеть'],
] as const satisfies readonly LearningEntry[]

export const seedVocabularyId = 'builtin-basic'

const buildWords = (entries: readonly LearningEntry[]): WordItem[] =>
  entries.map(([id, sourceText, targetText]) => ({
    id,
    sourceText,
    targetText,
    sourceLabel: 'qazaq tili',
    targetLabel: 'orys tili',
    level: 'A2',
    srs: srs(),
  }))

export const seedWords: WordItem[] = buildWords(basicEntries)

const seedVerbWords: WordItem[] = buildWords(verbEntries)

export const seedVocabularies: Vocabulary[] = [
  {
    id: seedVocabularyId,
    name: 'Базовый словарь',
    description: 'Стартовый набор слов для повторения.',
    category: 'mixed',
    isBuiltin: true,
    createdAt: 0,
    updatedAt: 0,
    words: seedWords,
  },
  {
    id: 'builtin-verbs-mini',
    name: 'Глаголы: мини-набор',
    description: 'Короткий словарь для проверки переключения между наборами.',
    category: 'verbs',
    isBuiltin: true,
    createdAt: 0,
    updatedAt: 0,
    words: seedVerbWords,
  },
]

